# Generated by Django 2.2.6 on 2023-09-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoProduto',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantidade_entrada', models.IntegerField(blank=True, db_column='quantidade_entrada', null=True)),
                ('quantidade_saida', models.IntegerField(blank=True, db_column='quantidade_saida', null=True)),
                ('dt_criacao', models.DateField(auto_now_add=True, db_column='dt_criacao', null=True)),
                ('dt_atualizacao', models.DateField(auto_now=True, db_column='dt_atualizacao', null=True)),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, related_name='movimento_produto', to='produto.Produto')),
            ],
            options={
                'db_table': 'movimento_produto',
            },
        ),
        migrations.AddIndex(
            model_name='movimentoproduto',
            index=models.Index(fields=['id', 'id_produto'], name='fields_movimento_produto_idx'),
        ),
    ]
