# Generated by Django 2.2.6 on 2023-09-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='codigo', error_messages={'unique': 'O campo codigo é único e já existe no banco de dados.'}, max_length=30, unique=True)),
                ('descricao', models.CharField(db_column='descricao', error_messages={'unique': 'O campo descricao é único e já existe no banco de dados.'}, max_length=200, unique=True)),
                ('ativo', models.BooleanField(db_column='ativo')),
                ('dt_criacao', models.DateField(auto_now_add=True, db_column='dt_criacao', null=True)),
                ('dt_atualizacao', models.DateField(auto_now=True, db_column='dt_atualizacao', null=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['id', 'codigo'], name='fields_produto_idx'),
        ),
    ]
