# Generated by Django 2.2.6 on 2023-09-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueFuturo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='quantidade')),
                ('dt_disponivel', models.DateField(db_column='dt_disponivel')),
                ('dt_criacao', models.DateField(auto_now_add=True, db_column='dt_criacao', null=True)),
                ('dt_atualizacao', models.DateField(auto_now=True, db_column='dt_atualizacao', null=True)),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, related_name='estoque_futuro', to='produto.Produto')),
            ],
            options={
                'db_table': 'estoque_futuro',
            },
        ),
        migrations.AddIndex(
            model_name='estoquefuturo',
            index=models.Index(fields=['id', 'id_produto'], name='fields_estoque_futuro_idx'),
        ),
    ]
